// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASD4-JrLqUu1sUYiJ4r4p2OdpwsmMMio0',
    appId: '1:372130039565:web:d11e9fe2cc5fc3cdfcd244',
    messagingSenderId: '372130039565',
    projectId: 'ngo-community',
    authDomain: 'ngo-community.firebaseapp.com',
    databaseURL: 'https://ngo-community-default-rtdb.firebaseio.com',
    storageBucket: 'ngo-community.appspot.com',
    measurementId: 'G-KHP967T7R4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBanHuJJVME2mU9KHXUKbekYAHIzajGIp8',
    appId: '1:372130039565:android:9a978039244fdcdafcd244',
    messagingSenderId: '372130039565',
    projectId: 'ngo-community',
    databaseURL: 'https://ngo-community-default-rtdb.firebaseio.com',
    storageBucket: 'ngo-community.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD62ttzWzueUaq_8tjJTGWQf2PBfPL1QQc',
    appId: '1:372130039565:ios:3caf649c7c4d7979fcd244',
    messagingSenderId: '372130039565',
    projectId: 'ngo-community',
    databaseURL: 'https://ngo-community-default-rtdb.firebaseio.com',
    storageBucket: 'ngo-community.appspot.com',
    androidClientId: '372130039565-0tsm7srqaqf1rhtnp28hj9649bbsn0tj.apps.googleusercontent.com',
    iosClientId: '372130039565-grigb71ocdqg95i3jbta3sk9ak6aa8un.apps.googleusercontent.com',
    iosBundleId: 'com.example.base',
  );
}
